package com.gcs.gRPCModbusAdapter.functions.args

enum class RegisterId(val value: Int) {
    TOTAL_POWER(0x00),
    EXPORT_POWER(0x08),
    IMPORT_POWER(0x0A),
    CURRENT_POWER(0x86),
    DEVICE_ID(0x15),
    CURRENT_VOLTAGE_PHASE1(0x80),
    CURRENT_VOLTAGE_PHASE2(0x81),
    CURRENT_VOLTAGE_PHASE3(0x82),
    CURRENT_AMPERAGE_PHASE1(0x83),
    CURRENT_AMPERAGE_PHASE2(0x84),
    CURRENT_AMPERAGE_PHASE3(0x85),
    WATER_TANK_AGGREGATED_STATUS(0x00),
    WATER_TANK_CMD_CONTROL(0x3e8);
}