management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
ports:
  entries: []
devices:
  entries: []

logging:
  config: classpath:logback-spring.xml

