management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
ports:
  entries:
    - name: COM4
      baudRate: 9600
      dataBits: 8
      parity: NONE
      stopBits: STOPBITS_1
