// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.2
// source: service.proto

package grpc2modbus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModbusDeviceService_SubscribeForDeviceData_FullMethodName = "/com.gcs.gRPCModbusAdapter.service.ModbusDeviceService/subscribeForDeviceData"
	ModbusDeviceService_WriteDeviceCommand_FullMethodName     = "/com.gcs.gRPCModbusAdapter.service.ModbusDeviceService/writeDeviceCommand"
)

// ModbusDeviceServiceClient is the client API for ModbusDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModbusDeviceServiceClient interface {
	SubscribeForDeviceData(ctx context.Context, in *Query, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	WriteDeviceCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error)
}

type modbusDeviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModbusDeviceServiceClient(cc grpc.ClientConnInterface) ModbusDeviceServiceClient {
	return &modbusDeviceServiceClient{cc}
}

func (c *modbusDeviceServiceClient) SubscribeForDeviceData(ctx context.Context, in *Query, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModbusDeviceService_ServiceDesc.Streams[0], ModbusDeviceService_SubscribeForDeviceData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Query, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModbusDeviceService_SubscribeForDeviceDataClient = grpc.ServerStreamingClient[Response]

func (c *modbusDeviceServiceClient) WriteDeviceCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, ModbusDeviceService_WriteDeviceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModbusDeviceServiceServer is the server API for ModbusDeviceService service.
// All implementations must embed UnimplementedModbusDeviceServiceServer
// for forward compatibility.
type ModbusDeviceServiceServer interface {
	SubscribeForDeviceData(*Query, grpc.ServerStreamingServer[Response]) error
	WriteDeviceCommand(context.Context, *Command) (*CommandResponse, error)
	mustEmbedUnimplementedModbusDeviceServiceServer()
}

// UnimplementedModbusDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModbusDeviceServiceServer struct{}

func (UnimplementedModbusDeviceServiceServer) SubscribeForDeviceData(*Query, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method SubscribeForDeviceData not implemented")
}
func (UnimplementedModbusDeviceServiceServer) WriteDeviceCommand(context.Context, *Command) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteDeviceCommand not implemented")
}
func (UnimplementedModbusDeviceServiceServer) mustEmbedUnimplementedModbusDeviceServiceServer() {}
func (UnimplementedModbusDeviceServiceServer) testEmbeddedByValue()                             {}

// UnsafeModbusDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModbusDeviceServiceServer will
// result in compilation errors.
type UnsafeModbusDeviceServiceServer interface {
	mustEmbedUnimplementedModbusDeviceServiceServer()
}

func RegisterModbusDeviceServiceServer(s grpc.ServiceRegistrar, srv ModbusDeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedModbusDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModbusDeviceService_ServiceDesc, srv)
}

func _ModbusDeviceService_SubscribeForDeviceData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModbusDeviceServiceServer).SubscribeForDeviceData(m, &grpc.GenericServerStream[Query, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModbusDeviceService_SubscribeForDeviceDataServer = grpc.ServerStreamingServer[Response]

func _ModbusDeviceService_WriteDeviceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModbusDeviceServiceServer).WriteDeviceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModbusDeviceService_WriteDeviceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModbusDeviceServiceServer).WriteDeviceCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// ModbusDeviceService_ServiceDesc is the grpc.ServiceDesc for ModbusDeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModbusDeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.gcs.gRPCModbusAdapter.service.ModbusDeviceService",
	HandlerType: (*ModbusDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "writeDeviceCommand",
			Handler:    _ModbusDeviceService_WriteDeviceCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribeForDeviceData",
			Handler:       _ModbusDeviceService_SubscribeForDeviceData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
