// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: service.proto

package grpc2modbus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceFunction int32

const (
	DeviceFunction_UNKNOWN                    DeviceFunction = 0
	DeviceFunction_TOTAL_POWER                DeviceFunction = 1
	DeviceFunction_EXPORT_POWER               DeviceFunction = 2
	DeviceFunction_IMPORT_POWER               DeviceFunction = 3
	DeviceFunction_CURRENT_POWER              DeviceFunction = 4
	DeviceFunction_CURRENT_VOLTAGE_PHASE1     DeviceFunction = 5
	DeviceFunction_CURRENT_VOLTAGE_PHASE2     DeviceFunction = 6
	DeviceFunction_CURRENT_VOLTAGE_PHASE3     DeviceFunction = 7
	DeviceFunction_CURRENT_AMPERAGE_PHASE1    DeviceFunction = 8
	DeviceFunction_CURRENT_AMPERAGE_PHASE2    DeviceFunction = 9
	DeviceFunction_CURRENT_AMPERAGE_PHASE3    DeviceFunction = 10
	DeviceFunction_WATER_TANK_COMBINED_STATUS DeviceFunction = 11
)

// Enum value maps for DeviceFunction.
var (
	DeviceFunction_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "TOTAL_POWER",
		2:  "EXPORT_POWER",
		3:  "IMPORT_POWER",
		4:  "CURRENT_POWER",
		5:  "CURRENT_VOLTAGE_PHASE1",
		6:  "CURRENT_VOLTAGE_PHASE2",
		7:  "CURRENT_VOLTAGE_PHASE3",
		8:  "CURRENT_AMPERAGE_PHASE1",
		9:  "CURRENT_AMPERAGE_PHASE2",
		10: "CURRENT_AMPERAGE_PHASE3",
		11: "WATER_TANK_COMBINED_STATUS",
	}
	DeviceFunction_value = map[string]int32{
		"UNKNOWN":                    0,
		"TOTAL_POWER":                1,
		"EXPORT_POWER":               2,
		"IMPORT_POWER":               3,
		"CURRENT_POWER":              4,
		"CURRENT_VOLTAGE_PHASE1":     5,
		"CURRENT_VOLTAGE_PHASE2":     6,
		"CURRENT_VOLTAGE_PHASE3":     7,
		"CURRENT_AMPERAGE_PHASE1":    8,
		"CURRENT_AMPERAGE_PHASE2":    9,
		"CURRENT_AMPERAGE_PHASE3":    10,
		"WATER_TANK_COMBINED_STATUS": 11,
	}
)

func (x DeviceFunction) Enum() *DeviceFunction {
	p := new(DeviceFunction)
	*p = x
	return p
}

func (x DeviceFunction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceFunction) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (DeviceFunction) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x DeviceFunction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceFunction.Descriptor instead.
func (DeviceFunction) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type DeviceCommand int32

const (
	DeviceCommand_UNKNOWN_COMMAND                       DeviceCommand = 0
	DeviceCommand_UPDATE_WATER_TANK_RULES               DeviceCommand = 1
	DeviceCommand_NOTIFY_WATER_TANK_WITH_ENERGY_BALANCE DeviceCommand = 2
)

// Enum value maps for DeviceCommand.
var (
	DeviceCommand_name = map[int32]string{
		0: "UNKNOWN_COMMAND",
		1: "UPDATE_WATER_TANK_RULES",
		2: "NOTIFY_WATER_TANK_WITH_ENERGY_BALANCE",
	}
	DeviceCommand_value = map[string]int32{
		"UNKNOWN_COMMAND":                       0,
		"UPDATE_WATER_TANK_RULES":               1,
		"NOTIFY_WATER_TANK_WITH_ENERGY_BALANCE": 2,
	}
)

func (x DeviceCommand) Enum() *DeviceCommand {
	p := new(DeviceCommand)
	*p = x
	return p
}

func (x DeviceCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (DeviceCommand) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x DeviceCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCommand.Descriptor instead.
func (DeviceCommand) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []*DeviceRequest       `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetRequest() []*DeviceRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type Command struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceName string                 `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Command    DeviceCommand          `protobuf:"varint,2,opt,name=command,proto3,enum=com.gcs.gRPCModbusAdapter.service.DeviceCommand" json:"command,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_IntPayload
	//	*Command_Items
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Command) GetCommand() DeviceCommand {
	if x != nil {
		return x.Command
	}
	return DeviceCommand_UNKNOWN_COMMAND
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetIntPayload() int32 {
	if x != nil {
		if x, ok := x.Payload.(*Command_IntPayload); ok {
			return x.IntPayload
		}
	}
	return 0
}

func (x *Command) GetItems() *StringList {
	if x != nil {
		if x, ok := x.Payload.(*Command_Items); ok {
			return x.Items
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_IntPayload struct {
	IntPayload int32 `protobuf:"varint,3,opt,name=intPayload,proto3,oneof"`
}

type Command_Items struct {
	Items *StringList `protobuf:"bytes,4,opt,name=items,proto3,oneof"`
}

func (*Command_IntPayload) isCommand_Payload() {}

func (*Command_Items) isCommand_Payload() {}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []string               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *StringList) GetItem() []string {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ReadRequests  []*Request             `protobuf:"bytes,2,rep,name=readRequests,proto3" json:"readRequests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceRequest) GetReadRequests() []*Request {
	if x != nil {
		return x.ReadRequests
	}
	return nil
}

type Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FunctionName          DeviceFunction         `protobuf:"varint,1,opt,name=functionName,proto3,enum=com.gcs.gRPCModbusAdapter.service.DeviceFunction" json:"functionName,omitempty"`
	ReadIntervalInSeconds uint32                 `protobuf:"varint,2,opt,name=readIntervalInSeconds,proto3" json:"readIntervalInSeconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetFunctionName() DeviceFunction {
	if x != nil {
		return x.FunctionName
	}
	return DeviceFunction_UNKNOWN
}

func (x *Request) GetReadIntervalInSeconds() uint32 {
	if x != nil {
		return x.ReadIntervalInSeconds
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	FunctionName  DeviceFunction         `protobuf:"varint,3,opt,name=functionName,proto3,enum=com.gcs.gRPCModbusAdapter.service.DeviceFunction" json:"functionName,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	DataType      string                 `protobuf:"bytes,5,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Response) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Response) GetFunctionName() DeviceFunction {
	if x != nil {
		return x.FunctionName
	}
	return DeviceFunction_UNKNOWN
}

func (x *Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Response) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Response) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Success       *bool                  `protobuf:"varint,2,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12!com.gcs.gRPCModbusAdapter.service\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x05Query\x12J\n" +
	"\arequest\x18\x01 \x03(\v20.com.gcs.gRPCModbusAdapter.service.DeviceRequestR\arequest\"\xe9\x01\n" +
	"\aCommand\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x01 \x01(\tR\n" +
	"deviceName\x12J\n" +
	"\acommand\x18\x02 \x01(\x0e20.com.gcs.gRPCModbusAdapter.service.DeviceCommandR\acommand\x12 \n" +
	"\n" +
	"intPayload\x18\x03 \x01(\x05H\x00R\n" +
	"intPayload\x12E\n" +
	"\x05items\x18\x04 \x01(\v2-.com.gcs.gRPCModbusAdapter.service.StringListH\x00R\x05itemsB\t\n" +
	"\apayload\" \n" +
	"\n" +
	"StringList\x12\x12\n" +
	"\x04item\x18\x01 \x03(\tR\x04item\"\x7f\n" +
	"\rDeviceRequest\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x01 \x01(\tR\n" +
	"deviceName\x12N\n" +
	"\freadRequests\x18\x02 \x03(\v2*.com.gcs.gRPCModbusAdapter.service.RequestR\freadRequests\"\x96\x01\n" +
	"\aRequest\x12U\n" +
	"\ffunctionName\x18\x01 \x01(\x0e21.com.gcs.gRPCModbusAdapter.service.DeviceFunctionR\ffunctionName\x124\n" +
	"\x15readIntervalInSeconds\x18\x02 \x01(\rR\x15readIntervalInSeconds\"\xf7\x01\n" +
	"\bResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tR\n" +
	"deviceName\x12U\n" +
	"\ffunctionName\x18\x03 \x01(\x0e21.com.gcs.gRPCModbusAdapter.service.DeviceFunctionR\ffunctionName\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bdataType\x18\x05 \x01(\tR\bdataType\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\"\x97\x01\n" +
	"\x0fCommandResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1d\n" +
	"\asuccess\x18\x02 \x01(\bH\x00R\asuccess\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\n" +
	"\n" +
	"\b_message*\xb0\x02\n" +
	"\x0eDeviceFunction\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vTOTAL_POWER\x10\x01\x12\x10\n" +
	"\fEXPORT_POWER\x10\x02\x12\x10\n" +
	"\fIMPORT_POWER\x10\x03\x12\x11\n" +
	"\rCURRENT_POWER\x10\x04\x12\x1a\n" +
	"\x16CURRENT_VOLTAGE_PHASE1\x10\x05\x12\x1a\n" +
	"\x16CURRENT_VOLTAGE_PHASE2\x10\x06\x12\x1a\n" +
	"\x16CURRENT_VOLTAGE_PHASE3\x10\a\x12\x1b\n" +
	"\x17CURRENT_AMPERAGE_PHASE1\x10\b\x12\x1b\n" +
	"\x17CURRENT_AMPERAGE_PHASE2\x10\t\x12\x1b\n" +
	"\x17CURRENT_AMPERAGE_PHASE3\x10\n" +
	"\x12\x1e\n" +
	"\x1aWATER_TANK_COMBINED_STATUS\x10\v*l\n" +
	"\rDeviceCommand\x12\x13\n" +
	"\x0fUNKNOWN_COMMAND\x10\x00\x12\x1b\n" +
	"\x17UPDATE_WATER_TANK_RULES\x10\x01\x12)\n" +
	"%NOTIFY_WATER_TANK_WITH_ENERGY_BALANCE\x10\x022\x82\x02\n" +
	"\x13ModbusDeviceService\x12s\n" +
	"\x16subscribeForDeviceData\x12(.com.gcs.gRPCModbusAdapter.service.Query\x1a+.com.gcs.gRPCModbusAdapter.service.Response\"\x000\x01\x12v\n" +
	"\x12writeDeviceCommand\x12*.com.gcs.gRPCModbusAdapter.service.Command\x1a2.com.gcs.gRPCModbusAdapter.service.CommandResponse\"\x00B\x82\x01\n" +
	"!com.gcs.gRPCModbusAdapter.serviceB\x16MeterManagementServiceP\x01ZCgithub.com/gregj77/gRPCModbusAdapter/grpc2modbus-sdk-go;grpc2modbusb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(DeviceFunction)(0),           // 0: com.gcs.gRPCModbusAdapter.service.DeviceFunction
	(DeviceCommand)(0),            // 1: com.gcs.gRPCModbusAdapter.service.DeviceCommand
	(*Query)(nil),                 // 2: com.gcs.gRPCModbusAdapter.service.Query
	(*Command)(nil),               // 3: com.gcs.gRPCModbusAdapter.service.Command
	(*StringList)(nil),            // 4: com.gcs.gRPCModbusAdapter.service.StringList
	(*DeviceRequest)(nil),         // 5: com.gcs.gRPCModbusAdapter.service.DeviceRequest
	(*Request)(nil),               // 6: com.gcs.gRPCModbusAdapter.service.Request
	(*Response)(nil),              // 7: com.gcs.gRPCModbusAdapter.service.Response
	(*CommandResponse)(nil),       // 8: com.gcs.gRPCModbusAdapter.service.CommandResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	5,  // 0: com.gcs.gRPCModbusAdapter.service.Query.request:type_name -> com.gcs.gRPCModbusAdapter.service.DeviceRequest
	1,  // 1: com.gcs.gRPCModbusAdapter.service.Command.command:type_name -> com.gcs.gRPCModbusAdapter.service.DeviceCommand
	4,  // 2: com.gcs.gRPCModbusAdapter.service.Command.items:type_name -> com.gcs.gRPCModbusAdapter.service.StringList
	6,  // 3: com.gcs.gRPCModbusAdapter.service.DeviceRequest.readRequests:type_name -> com.gcs.gRPCModbusAdapter.service.Request
	0,  // 4: com.gcs.gRPCModbusAdapter.service.Request.functionName:type_name -> com.gcs.gRPCModbusAdapter.service.DeviceFunction
	9,  // 5: com.gcs.gRPCModbusAdapter.service.Response.time:type_name -> google.protobuf.Timestamp
	0,  // 6: com.gcs.gRPCModbusAdapter.service.Response.functionName:type_name -> com.gcs.gRPCModbusAdapter.service.DeviceFunction
	9,  // 7: com.gcs.gRPCModbusAdapter.service.CommandResponse.time:type_name -> google.protobuf.Timestamp
	2,  // 8: com.gcs.gRPCModbusAdapter.service.ModbusDeviceService.subscribeForDeviceData:input_type -> com.gcs.gRPCModbusAdapter.service.Query
	3,  // 9: com.gcs.gRPCModbusAdapter.service.ModbusDeviceService.writeDeviceCommand:input_type -> com.gcs.gRPCModbusAdapter.service.Command
	7,  // 10: com.gcs.gRPCModbusAdapter.service.ModbusDeviceService.subscribeForDeviceData:output_type -> com.gcs.gRPCModbusAdapter.service.Response
	8,  // 11: com.gcs.gRPCModbusAdapter.service.ModbusDeviceService.writeDeviceCommand:output_type -> com.gcs.gRPCModbusAdapter.service.CommandResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[1].OneofWrappers = []any{
		(*Command_IntPayload)(nil),
		(*Command_Items)(nil),
	}
	file_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
