version: "3.3"
services:
  rs485-to-grpc:
    image: pejs77/grpc-modbus-adapter:1.0.43
    ports:
      - "8080:8080"
      - "9090:9090"
      - "5005:5005"
    environment:
      - "SPRING_PROFILES_ACTIVE=home"
      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -XX:MaxRAM=128m -Xss256k -XX:ActiveProcessorCount=1"
    volumes:
      - "/data/application-home.yaml:/BOOT-INF/classes/application-home.yaml"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
